[GOOGLE_CREDENTIALS]
type = "service_account"
project_id = "valiant-vault-358600"
private_key_id = "b26fa85dfb72f26449a69173804a5d3497fbf886"
private_key = """
-----BEGIN PRIVATE KEY-----
…your full key here…
-----END PRIVATE KEY-----
"""
client_email = "rx-ocr-service@valiant-vault-358600.iam.gserviceaccount.com"
client_id = "108495704787487717859"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/rx-ocr-service@valiant-vault-358600.iam.gserviceaccount.com"
