# .streamlit/secrets.toml
[GOOGLE_CREDENTIALS]
type = "service_account"
project_id = "valiant-vault-358600"
private_key_id = "b26fa85dfb72f26449a69173804a5d3497fbf886"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC9qp/gBc9TVBO9
Csb+4l5Dg1mLbkg7pX+Ohwauzhgzt1jMuLinqAgVZqOlRXuBHXp7O9Ym5QQHNRj4
s9I46zJ3uK8fmH5cbMgpTfddrNep8sBa6sOD1cJW0gix5se5SLuNlVCN751dsUMW
...rest of key lines...
-----END PRIVATE KEY-----
"""
client_email = "rx-ocr-service@valiant-vault-358600.iam.gserviceaccount.com"
client_id = "108495704787487717859"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/rx-ocr-service@valiant-vault-358600.iam.gserviceaccount.com"
