[GOOGLE_CREDENTIALS]
type = "service_account"
project_id = "valiant-vault-358600"
private_key_id = "b26fa85dfb72f26449a69173804a5d3497fbf886"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC9qp/gBc9TVBO9
Csb+4l5Dg1mLbkg7pX+Ohwauzhgzt1jMuLinqAgVZqOlRXuBHXp7O9Ym5QQHNRj4
s9I46zJ3uK8fmH5cbMgpTfddrNep8sBa6sOD1cJW0gix5se5SLuNlVCN751dsUMW
PILMvNlfADCB762YF76LHHjkdeedRnYAjeB7pYqfsBNHt7KDjv7lvyF3v8M8+5B2
mNJgWTJ0hueDySYz4t/Yl3PLw1Bc5cIzhLM0CRBPN3v50wPeIiWItgRgvoF14HAz
fU0U8Sk4Q4Uq/4sGhIyx3tVoCInyQVl/lsFTIsr6m7I5WhQPIJ7lIhIUA5AuYtFS
opSloADBAgMBAAECggEAEJiJ9bm8au+r7HoxcGMRWXn4T11+f42bLDb/bDNHZdsQ
r5UoPy9SScEZ55+9T05rhbX2JqAaaqEIRtbBOc7GszgbRrn6sI6qMwcJ8o3prwq5
LxtksTf2kc8+CIcHidxl4N0kV88UJ3sXwi3YSh7qLEhhdjUpLOpC93wtzdvNQPMf
NzanD2aoc+ibGPNNOEIgM0OfXBRKgegYuOsQ2rf9dClvUl4/BNK5u6w4J4ksO45s
K+cJE0A+mZkiONkDNtoCX2jY6r80+YAmNKUPBKU0TF8lwtGc/J4IFKJIOzTevyYo
V3Uo7aVpSffiKb4VDO4Q9kfqrqO64DzbrewUzVSrowKBgQDu1rOMQMbYWgEaW5Ki
pLB+pYYVZjVkoYXhWcPzTmMmIQDS2doW/UM8U+ivMNQZhWnQoJUEWm1rg8mDAcD3
ynsQ9CLNfq7nsb6EcJOyYon5iDYJhovjRWBCPSWHXsS8Ao7bY7yoc9XOxllC2Lyf
Gy+sqVMXUV8uuA/K6St5yo5VmwKBgQDLS234cYY+n7lUPDy29pS7Vu5makKJXZTF
f/206lNugn4AUNj3de/98gNlD009o7FCKSXKSsiglT748pGtFaEWnX5f0M0eY3Rd
m52dvupNdeiluBPcsI5w3PJodv2VpE0Q9CpB0VW86DQ7p2gNRWhkE+dmgF/3TgY+
jydi7y520wKBgQDnhGf3hLM79cMr8ahq0Inluj4HcFRBf/FvSLyRlWK3CzbpLRQj
RM1wJUZgzExNkO3Jtl+9IIsAtXcY7xJHIJe7D2zNFgglwD6V0yrYuHxWzprTEQF5
BT8R9oPyfQLn3PLt5/hwshiHn+3WxpHRCWFlVZ2d9Nr3RqTIZM4n+RmQEQKBgQCD
tc79069CC4GrDYvYjlE2PtAeEmIhVTv56T6aY+bCBlFUKw0m5oYiZRXF9+/3K4LA
...
-----END PRIVATE KEY-----
"""
client_email = "rx-ocr-service@valiant-vault-358600.iam.gserviceaccount.com"
client_id = "108495704787487717859"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/rx-ocr-service@valiant-vault-358600.iam.gserviceaccount.com"
